#!/usr/bin/env bash
# display information for subdomains

subdomain_info() {
	dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    subdomain_info "$2.$1" "$2"
else
    subdomain_info "www.$1" "www"
    subdomain_info "lb-01.$1" "lb-01"
    subdomain_info "web-01.$1" "web-01"
    subdomain_info "web-02.$1" "web-02"
fi
