#!/usr/bin/env bash
#a Bash script that transfers a file from our client to a server

FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4
ARGV=$#

if [ $ARGV -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3" 
fi

scp -o StringHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME@$IP:~/"
