#!/usr/bin/env/ bash
#installing nginx

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://https://github.com/hendrixxD/ permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
