#!/usr/bin/env/ bash
#installing nginx

sudo apt-get -y update
sudo apt-get -y install nginx

ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.github.com/hendrixxD;'/etc/nginx/sites-available/default
service nginx start
