#!/usr/bin/env bash
# Configures an Nginx server so that it returns an error page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm; index.nginx-debian.html
    location /redirect_me {
        return 301 http://betterredirect.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
