#!/usr/bin/env bash
# Configures an Nginx server so that it returns HTTP response header
# X-Severed-BY hostname

#sudo apt-get update
#sudo apt-get install -y nginx

sudo service nginx start
echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    add_header X-Severed-By: $HOSTNAME;
    index  index.html index.htm index.nginx-debian.html;
    location /redirect_me {
        return 301 http://betterredirect.com/;
    }
    error_page 404 /custom_404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload

