#!/usr/bin/env bash
#Configuring an ubuntu server

apt-get update 
apt-get install -y nginx
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "/server_name _;/a \
	\\\n\terror_page 404 /404.html; \
	\n\n\tadd_header X-Served-By: $(hostname); \
	\n\n\tlocation /redirect_me { \
	\n\t\treturn 301 https://github.com/hendrixxD; \
	\n\t}" /etc/nginx/sites-available/default
sudo service nginx restart
