#!/usr/bin/env bash
# A scripts that uses ICMP i.e ping command to check if an ip is available


if [ "$#" = 0 ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit
else
    ping -c 5 "$1"
fi
