#!/usr/bin/env bash
#Write a Bash script that displays a list of currently running processes.
#-Must show all processes, for all users, including those which might not have a TTY
#-Display in a user-oriented format
#-Show process hierarchy

#to list processes currently running on your system is to use the command ps (short for process status).
#To get information about all processes running on the system, use ps -A:
#The most used options with ps are a, u and x. This displays all processes running for all users on your system,# along with useful information such as the username of the process′ owner, CPU loads, the starting time of the #process, the command that initiated the process, etc.

ps aux
