#!/usr/bin/env bash
#
#    Displays FizzBuzz when the number is a multiple of 3 and 5
#    Displays Fizz when the number is multiple of 3
#    Displays Buzz when the number is a multiple of 5
#    Otherwise, displays the number
#    In a list format

i=1
while [ $i -le 100 ]
do
	if [[ $(( i % 3 )) -eq 0  && $(( i % 5 )) -eq 0 ]]
	then
		echo "FizBuzz"

	elif ((i % 3==0))
	then
		echo "Fizz"

	elif ((i % 5==0))
	then
		echo "Buzz"

	else
		echo "$i"
	fi
	((i++))
done
