#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.
#
#Your script should only display:
#
#    username
#    user id
#    Home directory path for the user

i=$(/etc/passwd)
while i
do
	#read | -grep "$USER"&&$(id -u)
	read -r | cut -d ":" -f 1, 3, 6
	((i++))
done

