#!/usr/bin/env bash
#Displays 'bad Luck' for the 4th iteration
#Displays 'good luck' for the 8th loop iteration
#Displays 'Best School' for the other iteration

i=1
while [[ $i -le 10 ]]; do

	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ];then
		echo "good luck"
	else 
		echo "Best School"
	fi
	((i++))
done
