#!/usr/bin/env bash
#Bash script that displays:
#-The content of the current directory
#-In a list format
#-Where only the part of the name after the first dash is displayed
#must use for loop

# SYNTAX FOR CUT:
#	cut OPTION... [FILE]...
#

files=$(ls)
for file in $files
do
	echo "$file" | cut -d "-" -f 2
done

