#!/usr/bin/env bash
#Bash script that displays:
#-The content of the current directory
#-In a list format
#-Where only the part of the name after the first dash is displayed
#must use for loop

for i in pwd;do
        ls | grep -
done
